server:
  servlet:
    context-path: /toyseven
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8000
  tomcat:
    connection-timeout: 120000
  
logging:
  level:
    root: info
    
spring:
  main:
    allow-bean-definition-overriding: true # Bean Overriding 활성화 (SecurityConfig 의 AuthenticationManager Bean 생성을 위해 추가) 
#  redis:
#    host: localhost
#    port: 8080
    
  pid:
    file: logfiles/toyseven/toyseven.pid
    
  devtools:
    livereload:
      enabled: true
      
  profiles:
    active: local
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
#    driver-class-name: org.h2.jdbcx.JdbcDataSource
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:toyseven;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1; #접속 URL
    username: test
    password: test
    type: com.zaxxer.hikari.HikariDataSource
    
    hikari: 
      maximum-pool-size: 10 
      minimumIdle: 9
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      maxLifetime: 30000 
#      connection-test-query: SELECT 1 
      data-source-properties: 
        cachePrepStmts: true 
        prepStmtCacheSize: 250 
        prepStmtCacheSqlLimit: 2048 
        useServerPrepStmts: true
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        cache:
          usesecondlevelcache: true
          usequerycache: false
          region:
            factoryclass: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        generatestatistics: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ymktest43@gmail.com # 비밀번호가 변경 된 상태입니다.
    password: test0134^^
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://toyseven-domain.auth.ap-northeast-2.amazoncognito.com/ap-northeast-2_xxxxxxxxx
          jwk-set-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_xxxxxxxxx/.well-known/jwks.json
        opaquetoken:
          client-id: xxxxxxxxxxxxxxxx
          
aws:
  cognito:
    domaim: https://xxxxxxx.auth.ap-northeast-2.amazoncognito.com/
          
api:
  key:
    station: 784e68756e73696c36334f5a426b4a
    weather: W7l3H2uvjTcxohee32V7uY9ulhXXV%2FZL6qkE%2B%2FeGen8hKezg5Yg2u0h9yKx6Fs28sehdVvyY4T6dqOOu8nBVoQ%3D%3D
    fineDust: W7l3H2uvjTcxohee32V7uY9ulhXXV%2FZL6qkE%2B%2FeGen8hKezg5Yg2u0h9yKx6Fs28sehdVvyY4T6dqOOu8nBVoQ%3D%3D
