server:
  servlet:
    context-path: /toyseven
  port: 8080
  tomcat:
    connection-timeout: 120000
  
logging:
  level:
    root: info
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  main:    allow-bean-definition-overriding: true
      
  security:  
    oauth2:  
      client:  
        registration:
          google:
            client-id: 903583187105-ntgridg041te8mr1rqe5h8bn6h126hp6.apps.googleusercontent.com
            client-secret: TPMWBQ6ulxDoHvHgOWFdPJ9b
            scope: profile,email
  redis:
    host: localhost
    port: 8080
    
  pid:
    file: logfiles/toyseven/toyseven.pid
    
  devtools:
    livereload:
      enabled: true
      
  profiles:
    active: local
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
#    driver-class-name: org.h2.jdbcx.JdbcDataSource
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:toyseven;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1; #접속 URL
    username: test
    password: test
    type: com.zaxxer.hikari.HikariDataSource
    
    hikari: 
      maximum-pool-size: 10 
      minimumIdle: 9
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      maxLifetime: 30000 
#      connection-test-query: SELECT 1 
      data-source-properties: 
        cachePrepStmts: true 
        prepStmtCacheSize: 250 
        prepStmtCacheSqlLimit: 2048 
        useServerPrepStmts: true
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        cache:
          usesecondlevelcache: true
          usequerycache: false
          region:
            factoryclass: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        generatestatistics: true
        
        
api:
  key:
    station: 784e68756e73696c36334f5a426b4a
